---
- name: Ensure sudo groups exist
  group:
    name: "{{ item }}"
    state: present
    system: true
  with_items:
    - "{{ tmxsudo_allow_group }}"
    - "{{ tmxsudo_nopasswd_group }}"

- name: Check if ubuntu user exists
  getent:
    database: passwd
    key: ubuntu
    fail_key: false
  register: ubuntu_exists

- name: Add ubuntu user to normal sudo group
  user:
    name: ubuntu
    groups: sudo
    append: yes
  when: "ubuntu_exists.ansible_facts.getent_passwd.ubuntu != []"

- name: Template main sudo config (sudoers)
  template:
    dest: "{{ tmxsudo_config_root }}/sudoers"
    group: "{{ root_group }}"
    mode: 0440
    owner: root
    src: sudoers.j2
    validate: visudo -cf %s

- name: Template sudo group config (sudoers.d)
  template:
    dest: "{{ tmxsudo_config_root }}/sudoers.d/10-groups"
    group: "{{ root_group }}"
    mode: 0440
    owner: root
    src: sudo_groups.j2
    validate: visudo -cf %s
