---
- name: Ensure sudo groups exist
  group:
    name: "{{ item }}"
    state: present
    system: true
  with_items:
    - "{{ tmxsudo_allow_group }}"
    - "{{ tmxsudo_nopasswd_group }}"

- name: Template main sudo config (sudoers)
  template:
    dest: "{{ tmxsudo_config_root }}/sudoers"
    group: "{{ root_group }}"
    mode: 0440
    owner: root
    src: sudoers.j2
    validate: visudo -cf %s

- name: Template sudo group config (sudoers.d)
  template:
    dest: "{{ tmxsudo_config_root }}/sudoers.d/10-groups"
    group: "{{ root_group }}"
    mode: 0440
    owner: root
    src: sudo_groups.j2
    validate: visudo -cf %s
