---
# tasks file for proactcloud.sudo
- name: Include Distro dependent vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
        - distro_default.yml
      paths:
        - 'vars'

- name: Include install tasks
  include: install.yml
  tags: [ install ]

- name: Include config tasks
  include: config.yml
  tags: [ config ]
